### PR TITLE
feat: use `tab_switch` instead of custom function

### PR DESCRIPTION
**Pull request by sxyazi**
Needs https://github.com/sxyazi/yazi/pull/1817/files#diff-a725ce31e234c8455228ed544e4a40296ac13c052e4221d8c07dd4cdf6986f9e to support the new `Tab.idx` property, you can download the nightly build from https://github.com/sxyazi/yazi/releases/tag/nightly

### CODE REVIEW

**Comment by sxyazi** [comment]
~~@dawsers Can you upload your `stylua.toml`, seems a lot of conflicts are caused by style~~

Never mind, conflicts resolved

**Comment by dawsers** [comment]
Thank you very much for doing all this and also adding the `idx` field to `Tab`. I really appreciate it

I had forgotten to run `.stylua.toml`. I have added it to the repo and run my `init.lua` through it. This way the diffs will be usable, as right now they are really not. Please, do the same so we can be on the same page with comparisons.

I have been using your version. The paradigm is quite different. I noticed a few things you may clarify for me in case I got it wrong.

* When I open dual-pane and start adding new tabs, each pane only has one tab. I can move to any of them using either numbers or `<Tab>`, but I don't know how many there are in total, and I cannot control the one shown on the right pane (it will always be the next to the one on the left). In my opinion, this doesn't follow the main idea of the classic dual pane manager, which is not just being able to see two directories at the same time, but also allowing to copy or move files from one pane to the other easily. Here you can copy or move files, but you cannot control where to without going through some extra mental effort:  go to the tab on the right pane by making it active in the left pane, find your destination directory there, go back to the previous tab, and copy. You could argue the number of keystrokes is probably similar in a simple case, but I find it less intuitive. Why would I want to have two panes if I can only interact with one? I can have the same workflow with just one pane and changing the active tab, while saving some real state.

* If I open yazi without dual-pane, create the tabs there and then switch to dual-pane, each header instead shows all the tabs (there is a glitch and the left one shows a bogus last tab, and the right one a duplicated last tab, but that is just a minor bug). I think creating the tabs inside or outside of dual-pane should not matter, and the header display should be the same.

* In this new paradigm, I could argue the only real advantage of dual-pane is seeing where you copy your files to (destination directory), but you are always limited to the tab following the source directory. One could write a plugin without all the dual pane fuss and pain which simply does that: copy files from `tab` to `tab + 1`, and the workflow would be the same: set destination directory in `tab+1`, go back to `tab` and copy/move.

* When I use a classic dual pane file manager, I usually have several tabs open, most of them always assigned to the same directories, which helps muscle memory. I can then set any of those tabs on any of the two panes and copy/move files between them. This allows me many combinations with just a few tabs open, and knowing easily where to find them. With the new paradigm, I always need to be changing the directory assigned to tabs, because I cannot control the destination except by modifying the tab following the source directory. I end up with lots of tabs and I don't know what there is in them.

* I also noticed `[` and `]` don't work any more, but that could be a problem with my configuration (?). EDIT: I got it, `tab_switch` is now native, of course.

I hope I understood correctly what you did. Now, please convince me :-)

**Comment by sxyazi** [comment]
Thank you for bringing up these issues. The more I read, the more I realize that my understanding differs significantly from yours. It seems you envision a combination of dual-pane and tabs, where each dual-pane view has its own independent tabs, or perhaps something like vifm, where each tab has its own dual-pane.

What I had in mind was something like ranger, treating each tab as a pane and rendering them together to form a dual-pane, making tabs and panes the same concept. I think I now understand why the code needs to be implemented this way; it does require a more complex approach, so this simplified PR might not make sense at all — sorry for the confusion.

Please let me know if I've misunderstood anything.

**Comment by dawsers** [comment]
Yes, I think we now understand what each other was chasing.

The current state of the plugin works similarly to [Total Commander](https://www.ghisler.com/) or [Double Commander](https://doublecmd.sourceforge.io/), where each of the two panes is independent, and has access to the full list of tabs, which work similarly to bookmarks.

You bring up an interesting idea: *vifm*. *vifm* is more like *vim*, where each "tab" is a particular configuration of the two panes. It would be like the snapshot or a workflow. I don't use *vifm* like that, I still use it more like *Total Commander*, but it is definitely useful and a good idea for future refinements. But for that to work properly, I still need to implement persistence, otherwise it would be quite cumbersome to rework those special tabs each time *yazi* starts.

**Comment by sxyazi** [comment]
Ah totally, that makes perfect sense, in this case I'm going to close this PR, thanks for the explanation with all the kindness and patience!

**Comment by dawsers** [comment]
No, thank you for taking the time, and also helping with the Tab `idx`, it has been really useful.

**Pull request closed without merging**
